config/routes.rb
Rails.application.routes.draw do

  rutarel = (ENV['RUTA_RELATIVA'] || 'cor1440/')
  scope rutarel do
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'

      # El siguiente para superar mala generación del action en el formulario
      # cuando se autentica mal (genera
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/')
        ruta = File.join(Rails.configuration.relative_url_root,
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
      end
    end
    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit',
        :as => 'editar_registro_usuario'
      put 'usuarios/:id' => 'devise/registrations#update',
        :as => 'registro_usuario'
    end

    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' }

    resources :zrcs, path_names: {new: 'nueva', edit: 'edita' }

    get 'proyectosfinancieros/:id/matriz_seguimiento' =>
      'cor1440_gen/proyectosfinancieros#matriz_seguimiento',
        as: 'matrizseguimiento'

    namespace :admin do
      ab = ::Ability.new
      ab.tablasbasicas.each do |t|
        if (t[0] == "")
          c = t[1].pluralize
          resources c.to_sym,
            path_names: { new: 'nueva', edit: 'edita' }
        end
      end
    end

    root 'sivel2_gen/hogar#index'
  end

  mount Sip::Engine, at: rutarel, as: 'sip'
  mount Mr519Gen::Engine, at: rutarel, as: 'mr519_gen'
  mount Heb412Gen::Engine, at: rutarel, as: 'heb412_gen'
  mount Cor1440Gen::Engine, at: rutarel, as: 'cor1440_gen'
  mount Sivel2Gen::Engine, at: rutarel, as: 'sivel2_gen'
end

app/models/cor1440_gen/actividad.rb
require 'cor1440_gen/concerns/models/actividad'

module Cor1440Gen
  class Actividad < ActiveRecord::Base
    include Cor1440Gen::Concerns::Models::Actividad
    include Sip::Localizacion

    has_many :actividad_solicitud, dependent: :delete_all,
      class_name: 'ActividadSolicitud',
      foreign_key: 'actividad_id'
    has_many :solicitud, through: :actividad_solicitud, 
      dependent: :delete_all,
      class_name: 'Sip::Solicitud'
    accepts_nested_attributes_for :solicitud,
      allow_destroy: true, reject_if: :all_blank
    accepts_nested_attributes_for :actividad_solicitud,
      allow_destroy: true, reject_if: :all_blank

    def presenta(atr)
      total= 0
      case atr.to_s
      when 'poblacion_total'
        total = poblacion_hombres_r_solore +
            poblacion_mujeres_r_solore +
            poblacion_sinsexo_solore
        return total
      when 'responsable_numerodocumento'
        self.responsable && self.responsable.numerodocumento ? 
          self.responsable.numerodocumento : ''
      when 'proyecto_centro_de_costo'
        self.proyectofinanciero.map(&:centrocosto).join(';')
      else
        presenta_cor1440_gen(atr)
      end
    end
  end
end

app/models/cor1440_gen/proyectofinanciero.rb
require 'cor1440_gen/concerns/models/proyectofinanciero'

module Cor1440Gen
  class Proyectofinanciero < ActiveRecord::Base
    include Cor1440Gen::Concerns::Models::Proyectofinanciero

    has_many :proyectofinanciero_solicitud, dependent: :delete_all,
      class_name: 'ProyectofinancieroSolicitud',
      foreign_key: 'proyectofinanciero_id'
    has_many :solicitud, through: :proyectofinanciero_solicitud, 
      dependent: :delete_all,
      class_name: 'Sip::Solicitud'
    accepts_nested_attributes_for :solicitud,
      allow_destroy: true, reject_if: :all_blank
    accepts_nested_attributes_for :proyectofinanciero_solicitud,
      allow_destroy: true, reject_if: :all_blank

  end
end

app/controllers/cor1440_gen/actividades_controller.rb
require_dependency "cor1440_gen/concerns/controllers/actividades_controller"

module Cor1440Gen
  class ActividadesController < Heb412Gen::ModelosController

    include Cor1440Gen::Concerns::Controllers::ActividadesController

    before_action :set_actividad, 
      only: [:show, :edit, :update, :destroy],
      exclude: [:contar]
    load_and_authorize_resource class: Cor1440Gen::Actividad


    def atributos_show
      [ 
        :id, 
        :fecha_localizada, 
        :nombre, 
        :responsable,
        :aprobadoobs,
        :proyectofinanciero,
        :actividadpf, 
        :objetivo,
        :respuestafor,
        :orgsocial,
        :listadoasistencia,
        :poblacion,
        :anexos,
        :solicitud
      ]
    end

    def atributos_index
      [ 
        :actividadpf, 
        :id, 
        :fecha_localizada, 
        :nombre, 
        :responsable,
        :aprobadoobs,
        :proyectofinanciero,
        :objetivo,
        :resultado,
        :poblacion_hombres_r,
        :poblacion_mujeres_r,
        :poblacion_sinsexo,
        :poblacion_total,
        :anexos
      ]
    end

    def atributos_form
      atributos_show - [:id, 'id', :actividadpf]
    end

    def registrar_en_bitacora
      true
    end

    def update
      update_cor1440_gen
    end


    def lista_params
      lista_params_cor1440_gen +
       [
        :asistencia_attributes => [
        :orgsocial_id,
        :externo,
        :telefono,
        :vereda,
        :id,
        :rangoedadac_id,
        :perfilorgsocial_id,
        :_destroy,
        :persona_attributes => [
          :apellidos, 
          :id, 
          :nombres, 
          :numerodocumento, 
          :sexo, 
          :tdocumento_id,
          :anionac,
          :mesnac,
          :dianac
         ]
        ]
       ] +
       [
         :actividad_solicitud_attributes => [
           :id,
           :_destroy,
           :solicitud_attributes => [
             :id,
             :usuario_id, 
             :fecha,
             :solicitud,
             :estadosol_id,
             :usuarionotificar_ids => []
           ]
         ]
       ]
    end

    def edit
      edit_cor1440_gen
      render layout: 'application'
    end

    def destroy
      aobs = ActividadSolicitud.where(actividad_id: @actividad.id)
      aobs.each do |ao|
        ao.destroy!
      end
      @actividad.destroy!
      redirect_to actividades_path,  :flash => { :success => "Actividad eliminada!" }
    end

  end
end

app/controllers/cor1440_gen/mindicadorespf_controller.rb
require_dependency "cor1440_gen/concerns/controllers/mindicadorespf_controller"

module Cor1440Gen
  class MindicadorespfController < Sip::ModelosController

    load_and_authorize_resource class: Cor1440Gen::Mindicadorpf
    include Cor1440Gen::Concerns::Controllers::MindicadorespfController


    def mideindicador_PNUD19(mind, ind, fini, ffin)
      res = ind.resultadopf
      relai = { 'PNUD19OB1R1I1' => 'PNUD19OB1R1A1',
                'PNUD19OB1R1I2' => 'PNUD19OB1R1A1',
                'PNUD19OB1R1I3' => 'PNUD19OB1R1A2',
                'PNUD19OB1R1I4' => 'PNUD19OB1R1A3',
                'PNUD19OB1R1I5' => 'PNUD19OB1R1A4',
                'PNUD19OB1R1I6' => 'PNUD19OB1R1A5',
                'PNUD19OB1R2I1' => 'PNUD19OB1R2A1',
                'PNUD19OB1R2I2' => 'PNUD19OB1R2A2',
                'PNUD19OB1R2I3' => 'PNUD19OB1R2A3',
                'PNUD19OB1R3I1' => 'PNUD19OB1R3A1',
                'PNUD19OB1R3I2' => 'PNUD19OB1R3A2',
                'PNUD19OB1R3I3' => 'PNUD19OB1R3A3'}

      if relai[ind.numero].nil?
        puts "Indicador desconocido #{ind.numero}"
        return [-1, '#', -1, '#', -1, '#', -1, '#']
      end

      actpf = res.actividadpf.where(nombrecorto: relai[ind.numero])
      if actpf.count == 0
        puts "No hay actividadpf con nombre #{relai[ind.numero]}"
        return [-1, '#', -1, '#', -1, '#', -1, '#']
      end
      if actpf.count > 1
        puts "Hay más de una actividadpf con nombre #{actpf[ind.numero]}"
        return [-1, '#', -1, '#', -1, '#', -1, '#']
      end
      lac = Cor1440Gen::Actividad.joins(:actividadpf).
        where('cor1440_gen_actividadpf.id=?', actpf.take.id).
        where('fecha >= ?', fini).
        where('fecha <= ?', ffin).
        pluck(:id).uniq
      resind = lac.count
      if resind > 0
        urlevrind = cor1440_gen.actividades_url +
          '?filtro[busid]='+lac.join(',')
      end
      [resind, urlevrind, -1, '#', -1, '#', -1, '#']
    end
    
    def mindicadorpf_params
      params.require(:mindicadorpf).permit(
        atributos_form - ["pmindicadorpf", :actividadpf] +
        [:actividadpf_ids => []] +
        [
          'pmindicadorpf_attributes' => [
            'fecha_localizada', 
            'finicio_localizada', 
            'ffin_localizada', 
            'restiempo', 
            'dmed1', 
            'urlev1', 
            'dmed2', 
            'urlev2', 
            'dmed3', 
            'urlev3', 
            'resind', 
            'rutaevidencia', 
            'meta', 
            'observaciones',
            'porcump', 
            'analisis', 
            'acciones', 
            'responsables', 
            'plazo', 
            'id', 
            '_destroy',
            'datointermedioti_pmindicadorpf_attributes' => [
              :valor,
              :rutaevidencia,
              :datointermedioti_id,
              :id
            ]
          ]
        ]
      ) 
    end

    def mideindicador_particular(mind, ind, fini, ffin)
      if ind.numero =~ /^PNUD19O/
        return mideindicador_PNUD19(mind, ind, fini, ffin)
      else
        return mideindicador_cor1440_gen(mind, ind,fini, ffin)
      end
    end

  end
end

app/controllers/cor1440_gen/pmsindicadorpf_controller.rb
require 'cor1440_gen/concerns/controllers/pmsindicadorpf_controller'

module Cor1440Gen
  class PmsindicadorpfController < ApplicationController

  load_and_authorize_resource class: Cor1440Gen::Mindicadorpf
  include Cor1440Gen::Concerns::Controllers::PmsindicadorpfController

    # GET /pmsindicadorpf/new
    def new
      if params[:mindicadorpf_id] && Cor1440Gen::Mindicadorpf.where(id: params[:mindicadorpf_id].to_i).count == 1
        mind = Cor1440Gen::Mindicadorpf.find(params[:mindicadorpf_id].to_i)
        fini = Date.today
        ffin = fini + 1.month
        restiempo = 'Mes'
        meta = 1
        observaciones = ''
        @pmindicadorpf = Cor1440Gen::Pmindicadorpf.create(
          mindicadorpf_id: mind.id,
          finicio: fini,
          ffin: ffin,
          restiempo: restiempo,
          meta: meta,
          observaciones: observaciones)
        if @pmindicadorpf.save
          respond_to do |format|
            format.js { render text: @pmindicadorpf.id.to_s }
            format.json { render json: @pmindicadorpf.id.to_s, status: :created }
            format.html { render inline: 'No implementado', 
                          status: :unprocessable_entity }
          end
        else
          render inline: 'No implementado', status: :unprocessable_entity 
        end
      else
        render inline: 'Faltó identificación de mindicadorpf', 
          status: :unprocessable_entity 
      end
    end
  end
end

app/controllers/cor1440_gen/proyectosfinancieros_controller.rb
require_dependency "cor1440_gen/concerns/controllers/proyectosfinancieros_controller"

module Cor1440Gen
  class ProyectosfinancierosController < Heb412Gen::ModelosController

    # No requiere autorización por ser clase a incluir en otras
    
    include Cor1440Gen::Concerns::Controllers::ProyectosfinancierosController

    before_action :set_proyectofinanciero,
      only: [:show, :edit, :update, :destroy]      
    skip_before_action :set_proyectofinanciero, only: [:validar]

    load_and_authorize_resource  class: Cor1440Gen::Proyectofinanciero,
      only: [:new, :create, :destroy, :edit, :update, :index, :show,
             :objetivospf]

    def registrar_en_bitacora
      true
    end


    def atributos_show
      [ 
        :id,
        :nombre,
        :titulo 
      ] +
      [ :financiador_ids =>  [] ] + [
        :sectorapc,
        :fechainicio_localizada,
        :fechacierre_localizada,
        :duracion,
        :anioformulacion,
        :mesformulacion,
        :fechaaprobacion_localizada,
        :fechaliquidacion_localizada,
        :estado,
        :dificultad,
        :responsable,
        :aprobadoobs,
        :proyectofinanciero_usuario,
      ] +
      [ :tipomoneda,
        :tasaej,
        :desembolso, 
        :informenarrativo,
        :informefinanciero,
        :informeauditoria,
        :marcologico,
        :anexo_proyectofinanciero,
        :solicitudes, 
        :caracterizacion, 
        :beneficiario,
        :plantillahcm,
      ]
    end

    def atributos_index
      atributos_index_cor1440
    end

    def matriz_seguimiento
      if !params || !params[:id] || Cor1440Gen::Proyectofinanciero.where(
          id: params[:id]).count == 0
        return
      end
      @registro = @proyectofinanciero = Cor1440Gen::Proyectofinanciero.find(
        params[:id])

      render :matriz_seguimiento, layout: 'application'
    end

    def validar_registro(registro, detalle)
      detalleini = detalle.clone
      if !registro.fechainicio && 
        ::ApplicationHelper::ESTADOS_APROBADO.include?(registro.estado)
        detalle << "No tiene fecha de inicio"
      elsif registro.fechainicio && registro.fechainicio < Date.new(2000, 1, 1)
        detalle << "Fecha de inicio anterior al 1.Ene.2000"
      end
      if !registro.fechacierre && 
        ::ApplicationHelper::ESTADOS_APROBADO.include?(registro.estado)
        detalle << "No tiene fecha de terminación"
      elsif registro.fechacierre && registro.fechainicio &&
        registro.fechacierre <= registro.fechainicio
        detalle << "Fecha de terminación posterior o igual a la de inicio"
      end
      validar_mas_registro(registro, detalle)
      return detalleini == detalle
    end

    def proyectofinanciero_params_si_anzorc
      proyectofinanciero_params_cor1440_gen - [
      ] + [
        :proyectofinanciero_solicitud_attributes => [
          :id,
          :_destroy,
          :solicitud_attributes => [
            :id,
            :usuario_id, 
            :fecha,
            :solicitud,
            :estadosol_id,
            :usuarionotificar_ids => []
          ]
        ]
      ]
    end

    def proyectofinanciero_params
      params.require(:proyectofinanciero).permit(
        proyectofinanciero_params_si_anzorc)
    end

  end
end

app/views/cor1440_gen/proyectosfinancieros/_form.html.erb
<%- if current_usuario.nil?  %>
  <li><a href="usuarios/sign_in">Iniciar Sesión</a>
<%- else  %>
  <article>
  <%= simple_form_for @registro, 
    url: modelo_path(@registro),
    html: { } do |f| 
  %>
    <div data-role="content" class="form-inputs">
      <div id="errores">
        <% if f.object.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-error">
              <!--%= pluralize(f.object.errors.count, "error") %-->.
            </div>
            <ul>
              <% f.object.errors.messages.each do |msg| %>
                <li>* <%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.error_notification %>
      </div>

      <div role="tabpanel">
        <ul class="nav nav-tabs" role="tablist">
          <% if can? :manage, @registro %>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link active" 
                      id="basicos-pestana"
                      aria-selected="true" 
                      aria-controls="basicos" 
                      role="tab" 
                      data-bs-toggle="tab"
                      data-bs-target="#basicos"
                      type="button">
                Datos básicos
              </button>
            </li>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link" 
                      id="recursoshumanos-pestana"
                      data-bs-target="#recursoshumanos" 
                      aria-controls="recursoshumanos" 
                      role="tab" 
                      type="button"
                      data-bs-toggle="tab">
                Recursos humanos
              </button>
            </li>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link" 
                      id="recursoseconomicos-pestana"
                      data-bs-target="#recursoseconomicos" 
                      aria-controls="recursoseconomicos" 
                      role="tab"
                      type="button"
                      data-bs-toggle="tab">
                Recursos económicos y desembolsos
              </button>
            </li>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link"
                      id="informes-pestana"
                      data-bs-target="#informes"  
                      aria-controls="informes" 
                      role="tab" 
                      type="button"
                      data-bs-toggle="tab">
                Informes y auditorias
              </button>
            </li>
          <% end %>
          <% if can? :edit, @registro %>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link"
                      id="marcologico-pestana"
                      data-bs-target="#marcologico"  
                      aria-controls="marcologico" 
                      role="tab" 
                      type="button"
                      data-bs-toggle="tab">
                Marco Lógico
              </button>
            </li>
          <% end %>
          <% if can? :manage, @registro%>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link"
                      id="anexos-pestana"
                      data-bs-target="#anexos"  
                      aria-controls="anexos" 
                      role="tab" 
                      type="button"
                      data-bs-toggle="tab">
                Anexos
              </button>
            </li>
            <li role="presentation" class="nav-item">
              <button class="enviarautomatico_y_repintapf nav-link"
                      id="psolicitudes-pestana"
                      data-bs-target="#psolicitudes" 
                      aria-controls="psolicitudes" 
                      role="tab" 
                      type="button"
                      data-bs-toggle="tab">
                Observaciones / Otros
              </button>
            </li>
          <% end %>
        </ul>
        <div class="tab-content">
          <% if can? :manage, @registro%>
            <div class="tab-pane fade active show"
                 role="tabpanel"  
                 aria-labelledby="basicos-pestana"
                 id="basicos">
              <%= render 'basicos', :f => f %>
            </div> 

            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="recursoshumanos-pestana"
                 id="recursoshumanos">
              <%= render 'recursoshumanos', :f => f %>
            </div>

            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="recursoseconomicos-pestana"
                 id="recursoseconomicos">
              <%= render 'recursoseconomicos', :f => f %>
            </div>

            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="informes-pestana"
                 id="informes">
              <%= render 'informes', :f => f %>
            </div>

            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="contabilidad-pestana"
                 id="contabilidad">
              <%= render 'contabilidad', :f => f %>
            </div>

            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="datosfinanciador-pestana"
                 id="datosfinanciador">
              <%= render 'datosfinanciador', :f => f %>
            </div>
          <% end %> 
          <% if can? :edit, @registro %>
            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="marcologico-pestana"
                 id="marcologico">
              <%= render 'marcologico', :f => f %>
            </div>
          <% end %> 
          <% if can? :manage, @registro%>
            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="anexos-pestana"
                 id="anexos">
              <% if f.object.id.nil? %>
                <p>Antes de agregar anexos se debe guardar el compromiso institucional</p>
              <% else %>
                <%= render 'anexos', :f => f %> 
              <% end %>
            </div>
            <div class="tab-pane fade" 
                 role="tabpanel" 
                 aria-labelledby="psolicitudes-pestana"
                 id="psolicitudes">
              <%= render 'psolicitudes', :f => f %>
            </div>
          <% end %> 

        </div> <!-- tab-content -->
      </div> <!-- tabpanel -->
    </div> <!-- form-inputs -->

    <div class="form-actions" style="text-align: center">
      <% if controller.registrar_en_bitacora %>
        <input class='bitacora_cambio' id='proyectofinanciero_bitacora_cambio' 
               name='proyectofinanciero[bitacora_cambio]' type='hidden'>
      <% end %>
      <%= f.button :submit, 'Validar y Guardar', :class => 'btn btn-primary',
        'data-turbo' => false %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        proyectosfinancieros_path, :class => 'btn' %>
    </div> <!-- form-action -->
  <% end %> <!-- simple_form_for @proyectofinanciero -->
  </article>
<% end -%> <!-- else -->

app/views/cor1440_gen/proyectosfinancieros/_psolicitudes.html.erb
<%= render partial: 'sip/solicitudes/tabla_solicitudes', 
  locals: {f: f, relacion: :proyectofinanciero_solicitud}
%>

<%= f.association :caracterizacion,
  collection: Mr519Gen::Formulario.all,
  value_method: :id,
  label_method: :presenta_nombre,
  input_html: {class: 'chosen-select'}
%>
<%= f.association :beneficiario,
  collection: Sip::Persona.all,
  value_method: :id,
  label_method: :presenta_nombre,
  input_html: {class: 'chosen-select'}
%>
<%= f.association :plantillahcm,
  collection: Heb412Gen::Plantillahcm.all,
  value_method: :id,
  label_method: :presenta_nombre,
  input_html: {class: 'chosen-select'}

%>

app/views/cor1440_gen/proyectosfinancieros/_show_campo_aprobadoobs.html.erb
<%
    estado = :INDEF
    gd = Usuario.where(rol: Ability::ROLDIR)
    @registro.solicitud.where(usuario_id: gd.pluck(:id)).each do |o|
      if o.estadosol_id == Sip::Estadosol::NOAPROBADO
        estado = :MAL
      elsif o.estadosol_id == nil && estado != :MAL
        estado = :VACIO
      elsif o.estadosol_id == Sip::Estadosol::APROBADO && estado == :INDEF
        estado = :BIEN
      end
    end
%>

<% if estado == :BIEN then %>
  <span style="color: green">☑<span>
<% elsif estado == :MAL %>
  <span style="color: red">☒</span>
<% else %>
  <span style="color: orange">☐</span>
<% end %>

app/views/cor1440_gen/proyectosfinancieros/_show_mas_acciones.html.erb
<% if can? :manage, Cor1440Gen::Proyectofinanciero %>
  <%= link_to 'Prototipo de matriz de seguimiento', 
    main_app.matrizseguimiento_path(@registro.id),
    class: 'btn btn-default' 
  %>
<% end %>

app/views/cor1440_gen/proyectosfinancieros/matriz_seguimiento.html.erb
<%= 
  props = {}
  props['actividadespf'] = @proyectofinanciero.actividadpf.
    map { |a| 
        {
          pf_id: a.proyectofinanciero_id, 
          objetivopf_id: a.resultadopf_id ? 
            a.resultadopf.objetivopf_id : '',
          resultadopf_id: a.resultadopf_id,
          resultadopf_codigo: a.resultadopf_id ?
            a.resultadopf.codigo_completo : '',
          resultadopf_titulo: a.resultadopf_id ?
            a.resultadopf.resultado : '',
          actividadpf_id: a.id,
          codigo: a.nombrecorto,
          titulo: a.titulo
        }
       }
  react_component('MatrizSeguimiento', props) 
%>